require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MediaVehiclesController do

  # This should return the minimal set of attributes required to create a valid
  # MediaVehicle. As you add validations to MediaVehicle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MediaVehiclesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all media_vehicles as @media_vehicles" do
      media_vehicle = MediaVehicle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:media_vehicles).should eq([media_vehicle])
    end
  end

  describe "GET show" do
    it "assigns the requested media_vehicle as @media_vehicle" do
      media_vehicle = MediaVehicle.create! valid_attributes
      get :show, {:id => media_vehicle.to_param}, valid_session
      assigns(:media_vehicle).should eq(media_vehicle)
    end
  end

  describe "GET new" do
    it "assigns a new media_vehicle as @media_vehicle" do
      get :new, {}, valid_session
      assigns(:media_vehicle).should be_a_new(MediaVehicle)
    end
  end

  describe "GET edit" do
    it "assigns the requested media_vehicle as @media_vehicle" do
      media_vehicle = MediaVehicle.create! valid_attributes
      get :edit, {:id => media_vehicle.to_param}, valid_session
      assigns(:media_vehicle).should eq(media_vehicle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MediaVehicle" do
        expect {
          post :create, {:media_vehicle => valid_attributes}, valid_session
        }.to change(MediaVehicle, :count).by(1)
      end

      it "assigns a newly created media_vehicle as @media_vehicle" do
        post :create, {:media_vehicle => valid_attributes}, valid_session
        assigns(:media_vehicle).should be_a(MediaVehicle)
        assigns(:media_vehicle).should be_persisted
      end

      it "redirects to the created media_vehicle" do
        post :create, {:media_vehicle => valid_attributes}, valid_session
        response.should redirect_to(MediaVehicle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved media_vehicle as @media_vehicle" do
        # Trigger the behavior that occurs when invalid params are submitted
        MediaVehicle.any_instance.stub(:save).and_return(false)
        post :create, {:media_vehicle => {}}, valid_session
        assigns(:media_vehicle).should be_a_new(MediaVehicle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MediaVehicle.any_instance.stub(:save).and_return(false)
        post :create, {:media_vehicle => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested media_vehicle" do
        media_vehicle = MediaVehicle.create! valid_attributes
        # Assuming there are no other media_vehicles in the database, this
        # specifies that the MediaVehicle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MediaVehicle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => media_vehicle.to_param, :media_vehicle => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested media_vehicle as @media_vehicle" do
        media_vehicle = MediaVehicle.create! valid_attributes
        put :update, {:id => media_vehicle.to_param, :media_vehicle => valid_attributes}, valid_session
        assigns(:media_vehicle).should eq(media_vehicle)
      end

      it "redirects to the media_vehicle" do
        media_vehicle = MediaVehicle.create! valid_attributes
        put :update, {:id => media_vehicle.to_param, :media_vehicle => valid_attributes}, valid_session
        response.should redirect_to(media_vehicle)
      end
    end

    describe "with invalid params" do
      it "assigns the media_vehicle as @media_vehicle" do
        media_vehicle = MediaVehicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MediaVehicle.any_instance.stub(:save).and_return(false)
        put :update, {:id => media_vehicle.to_param, :media_vehicle => {}}, valid_session
        assigns(:media_vehicle).should eq(media_vehicle)
      end

      it "re-renders the 'edit' template" do
        media_vehicle = MediaVehicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MediaVehicle.any_instance.stub(:save).and_return(false)
        put :update, {:id => media_vehicle.to_param, :media_vehicle => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested media_vehicle" do
      media_vehicle = MediaVehicle.create! valid_attributes
      expect {
        delete :destroy, {:id => media_vehicle.to_param}, valid_session
      }.to change(MediaVehicle, :count).by(-1)
    end

    it "redirects to the media_vehicles list" do
      media_vehicle = MediaVehicle.create! valid_attributes
      delete :destroy, {:id => media_vehicle.to_param}, valid_session
      response.should redirect_to(media_vehicles_url)
    end
  end

end
